# Generated by Django 5.1.2 on 2024-10-25 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='kilogram',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='кг'),
        ),
        migrations.AddField(
            model_name='product',
            name='liter',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='л'),
        ),
    ]
